name: curo_combis
description: "Una aplicación móvil para la gestión de combis, que permite a los usuarios reservar viajes, ver rutas y horarios, y más."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0

  flutter_map: ^6.2.1
  latlong2: ^0.9.1

  geolocator: ^10.1.0

  sqflite: ^2.3.3+1
  path: ^1.9.0

  provider: ^6.1.2

  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mascota/
